// ── Blog Post Registry ────────────────────────────────────────────────────────
// Single source of truth for all blog post metadata.
// Adding a new post: add an entry here + create app/blog/_content/[slug].tsx

export interface BlogCategory {
  slug: string;
  label: string;
  color: string;
  description: string;
}

export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  author: string;
  date: string;
  readTime: string;
  categorySlug: string;
  gradient: string;
  image: string;
  /** Metadata for the individual post page */
  metaTitle?: string;
  metaDescription?: string;
}

export const BLOG_CATEGORIES: BlogCategory[] = [
  { slug: "family",       label: "Family",       color: "#2E6B3E", description: "Half term plans, days out and activities that work with kids." },
  { slug: "seasonal",     label: "Seasonal",     color: "#1C4A5A", description: "When to visit, what to expect, and seasonal tips." },
  { slug: "food",         label: "Food",         color: "#8B3A3A", description: "Honest restaurant reviews and places to eat in Formby." },
  { slug: "wildlife",     label: "Wildlife",     color: "#8B6040", description: "Red squirrels, birdwatching and Sefton Coast nature." },
  { slug: "walks",        label: "Walks",        color: "#1A5C3A", description: "Pinewoods trails, coastal walks and what to bring." },
  { slug: "conservation", label: "Conservation", color: "#4A6B1C", description: "The wildlife and habitat work that makes Formby special." },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "things-to-do-formby-half-term",
    title: "Things to Do in Formby During Half Term: Family Guide",
    excerpt: "Planning half term in Formby with the kids? Here's what actually works (and what I'd skip).",
    author: "Clare",
    date: "February 20, 2026",
    readTime: "8 min read",
    categorySlug: "family",
    gradient: "linear-gradient(135deg, #1C3220 0%, #2E6B3E 100%)",
    image: "/blog-card-family.webp",
  },
  {
    slug: "formby-beach-weather-guide",
    title: "The Formby Beach Weather Guide: When to Visit (& When to Skip)",
    excerpt: "After 10 years living here, I've learned when Formby Beach is brilliant and when it's just windy.",
    author: "Clare",
    date: "February 18, 2026",
    readTime: "6 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E7A9A 100%)",
    image: "/blog-card-seasonal.webp",
  },
  {
    slug: "where-to-eat-formby-with-kids",
    title: "Best Restaurants in Formby for Families: Our Honest Review",
    excerpt: "Four kids. Fussy eaters. Weekend sanity maintenance. Here are the restaurants that actually work for us.",
    author: "Clare",
    date: "February 15, 2026",
    readTime: "7 min read",
    categorySlug: "food",
    gradient: "linear-gradient(135deg, #5C1A1A 0%, #8B3A3A 100%)",
    image: "/blog-card-food.webp",
  },
  {
    slug: "red-squirrels-formby-spotting-guide",
    title: "How to Actually See Red Squirrels in Formby: Local Tips",
    excerpt: "Yes, they're here. Yes, they're cute. But no, you won't see them if you visit at 2pm on a Saturday.",
    author: "Clare",
    date: "February 12, 2026",
    readTime: "5 min read",
    categorySlug: "wildlife",
    gradient: "linear-gradient(135deg, #8B6040 0%, #A8764A 100%)",
    image: "/blog-card-wildlife.webp",
  },
  {
    slug: "formby-pinewoods-walking-guide",
    title: "Walking in Formby Pinewoods: Trails, Tips & What to Bring",
    excerpt: "The Pinewoods are gorgeous, but come unprepared and you'll be miserable. Here's what I've learned.",
    author: "Clare",
    date: "February 10, 2026",
    readTime: "6 min read",
    categorySlug: "walks",
    gradient: "linear-gradient(135deg, #1A5C3A 0%, #2E8B5A 100%)",
    image: "/blog-card-walks.webp",
  },
  {
    slug: "natterjack-toads-formby",
    title: "Natterjack Toads at Formby: Britain's Rarest Amphibian",
    excerpt: "I had no idea these existed until five years ago. Turns out I'd been walking past a nationally important breeding site every week.",
    author: "Clare",
    date: "February 22, 2026",
    readTime: "5 min read",
    categorySlug: "conservation",
    gradient: "linear-gradient(135deg, #1C3220 0%, #4A6B1C 100%)",
    image: "/natterjack-pond.webp",
  },
  {
    slug: "formby-day-trip-from-liverpool",
    title: "Formby Day Trip from Liverpool: The Honest Guide",
    excerpt: "25 minutes on the Merseyrail. Beach, pinewoods, red squirrels, a decent lunch. Here's how to do it properly: and what most day trip guides miss.",
    author: "Clare",
    date: "March 12, 2026",
    readTime: "7 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E6B3E 100%)",
    image: "/blog-card-day-trip.webp",
    metaTitle: "Formby Day Trip from Liverpool (or Manchester): Honest Local Guide",
    metaDescription: "How to do a Formby day trip from Liverpool properly. Train times, what to do, where to eat, and how long you actually need. Written by a Formby local.",
  },
  {
    slug: "dogs-formby-beach",
    title: "Can You Take Dogs to Formby Beach? Everything Worth Knowing",
    excerpt: "Short answer: yes. Longer answer: it depends on the time of year and which part of the beach you're on. Here's the honest version.",
    author: "Clare",
    date: "March 13, 2026",
    readTime: "6 min read",
    categorySlug: "wildlife",
    gradient: "linear-gradient(135deg, #1C3220 0%, #1A5C3A 100%)",
    image: "/blog-card-dogs-beach.webp",
    metaTitle: "Can You Take Dogs to Formby Beach? Rules, Seasons & Where to Walk",
    metaDescription: "Yes: dogs are allowed at Formby Beach, but seasonal restrictions apply May to September. Full guide to which sections, where to walk, and dog-friendly pubs nearby.",
  },
  {
    slug: "crosby-beach-iron-men-formby",
    title: "Crosby Beach and the Iron Men: How to Add it to a Formby Day Out",
    excerpt: "100 cast-iron figures standing in the sea. 20 minutes from Formby. Free. Most people who've lived near here for years have never been.",
    author: "Clare",
    date: "March 14, 2026",
    readTime: "6 min read",
    categorySlug: "walks",
    gradient: "linear-gradient(135deg, #1C3220 0%, #2A4A8B 100%)",
    image: "/blog-card-crosby-iron-men.webp",
    metaTitle: "Crosby Beach Iron Men: Visiting Another Place + Combining with Formby",
    metaDescription: "Antony Gormley's Another Place at Crosby Beach is 20 minutes from Formby. How to combine both into one day: tide timing, parking, and what to actually expect.",
  },
  {
    slug: "spring-formby-beach-april",
    title: "Formby Beach in Spring: Why April Is the Best Month to Visit",
    excerpt: "April at Formby is brilliant. The beach is back, the dunes are greening up, the red squirrels are out and about, and it's not yet the summer crowds. Here's what makes spring the best time to visit.",
    author: "Clare",
    date: "March 17, 2026",
    readTime: "6 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E6B3E 100%)",
    image: "/blog-card-spring-formby.webp",
    metaTitle: "Formby Beach in April: Spring Visit Guide, What to Expect",
    metaDescription: "April is one of the best months to visit Formby Beach. Fewer crowds, green dunes, red squirrels active, and the Natterjack Toads starting to call. Practical guide to spring at Formby.",
  },
  {
    slug: "best-cafes-formby-village",
    title: "Best Cafes in Formby Village: Where to Eat, Drink and Sit Down",
    excerpt: "Formby village has a quiet little cafe scene that most visitors miss entirely. A handful of independents doing good coffee, decent cake, and proper lunches. Here's where to go.",
    author: "Clare",
    date: "March 18, 2026",
    readTime: "5 min read",
    categorySlug: "food",
    gradient: "linear-gradient(135deg, #8B3A3A 0%, #4A2A1A 100%)",
    image: "/blog-card-cafes-formby.webp",
    metaTitle: "Best Cafes in Formby Village: Independent Coffee Shops and Lunch Spots",
    metaDescription: "The honest guide to cafes in Formby village: which ones are worth it, what to order, and where to go after the beach. From the NT cafe to village independents.",
  },
  // ── April 2026 posts ──────────────────────────────────────────────────────
  {
    slug: "easter-at-formby-beach-2026",
    title: "Easter at Formby Beach 2026: What to Expect and How to Do It Right",
    excerpt: "Four days, a beach, a pine wood, possibly a red squirrel, and 40,000 other people with the same idea. Here's how to do Easter at Formby without the stress.",
    author: "Clare",
    date: "April 3, 2026",
    readTime: "6 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E6B3E 100%)",
    image: "/blog-easter-formby.jpg",
    metaTitle: "Easter at Formby Beach 2026: What to Expect",
    metaDescription: "Everything you need to know about visiting Formby Beach at Easter 2026. When to arrive, where to park, red squirrels, and where to eat after. Written by a Formby local.",
  },
  {
    slug: "formby-open-2026-base",
    title: "Why Formby Makes a Better Base Than Southport for The Open 2026",
    excerpt: "Royal Birkdale is in Birkdale. But the train to Birkdale station stops in Formby first. Here's why staying in Formby for Open week might be the smarter call.",
    author: "Clare",
    date: "April 3, 2026",
    readTime: "5 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C3220 0%, #1C4A5A 100%)",
    image: "/blog-formby-open-base.jpg",
    metaTitle: "Staying in Formby for The Open 2026: Is It Worth It?",
    metaDescription: "The Open Championship is at Royal Birkdale in July 2026. Formby is 20 minutes away by train. Here's why it might make a better base than central Southport, and what to know before you book.",
  },
  {
    slug: "wild-garlic-formby-pinewoods",
    title: "Wild Garlic in Formby Pinewoods: Where to Find It and What to Do With It",
    excerpt: "April is the month the pinewoods turn white with wild garlic. If you've never walked through it, you're missing one of the genuinely good things about living near here.",
    author: "Clare",
    date: "April 4, 2026",
    readTime: "5 min read",
    categorySlug: "wildlife",
    gradient: "linear-gradient(135deg, #1A5C3A 0%, #4A6B1C 100%)",
    image: "/blog-wild-garlic-pinewoods.jpg",
    metaTitle: "Wild Garlic at Formby: Where to Find It in April",
    metaDescription: "April is wild garlic season in the Formby pinewoods. Where to walk to find it, when it peaks, what it smells like, and what to do with it if you pick some. Written by a Formby local.",
  },
  {
    slug: "formby-village-walk-guide",
    title: "Formby Village Walk: Chapel Lane, the High Street, and What's Worth Stopping For",
    excerpt: "Formby village has more to it than most people realise. A proper village high street, independent shops, a couple of good pubs, and enough to keep you occupied for a proper afternoon. Here's how to do it.",
    author: "Clare",
    date: "March 19, 2026",
    readTime: "5 min read",
    categorySlug: "walks",
    gradient: "linear-gradient(135deg, #1A5C3A 0%, #3A5C1A 100%)",
    image: "/blog-card-village-walk.webp",
    metaTitle: "Formby Village Walk: Chapel Lane, High Street & Things to See",
    metaDescription: "A guide to walking around Formby village: Chapel Lane boutiques, independent shops, the best pubs and cafes, and how long it actually takes. Good for a rainy afternoon or post-beach wind-down.",
  },
  {
    slug: "left-bank-brasserie-formby",
    title: "Left Bank Brasserie Formby: An Honest Review",
    excerpt: "Formby's fanciest restaurant. Worth the price? Worth booking ahead? Worth dressing up for? After going twice, here's where I actually land on it.",
    author: "Clare",
    date: "April 13, 2026",
    readTime: "6 min read",
    categorySlug: "food",
    gradient: "linear-gradient(135deg, #5C1A1A 0%, #8B3A3A 100%)",
    image: "/blog-card-food.webp",
    metaTitle: "Left Bank Brasserie Formby Review 2026: Is It Worth It?",
    metaDescription: "An honest review of Left Bank Brasserie in Formby village. Food, service, prices and whether it's actually worth the booking. Written by a local who's been twice.",
  },
  {
    slug: "blackpool-or-formby-family-day-out",
    title: "Blackpool or Formby for a Family Day Out? Clare's Honest Answer",
    excerpt: "I've done both with four kids. Here's the straight comparison — what Blackpool does well, what Formby does well, and how to decide which one is actually right for your family.",
    author: "Clare",
    date: "April 2, 2026",
    readTime: "7 min read",
    categorySlug: "family",
    gradient: "linear-gradient(135deg, #1C3220 0%, #2E6B3E 100%)",
    image: "/blog-blackpool-formby-family.jpg",
    metaTitle: "Blackpool or Formby for a Family Day Out? Honest Comparison",
    metaDescription: "Blackpool has the rides and the Illuminations. Formby has the pinewoods, red squirrels and a quiet beach. Which one is right depends on your family. Here's the honest answer from a Formby local.",
  },
  {
    slug: "formby-day-trip-from-blackpool",
    title: "Formby as a Day Trip from Blackpool: How to Do It Properly",
    excerpt: "Blackpool to Formby is 45 minutes by car or just under an hour by train. Beach, pinewoods, red squirrels, a decent lunch. Here's how to do it right and what most visitors miss.",
    author: "Clare",
    date: "April 2, 2026",
    readTime: "6 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E6B3E 100%)",
    image: "/blog-formby-from-blackpool-train.jpg",
    metaTitle: "Formby Day Trip from Blackpool: Train, Driving, What to Do",
    metaDescription: "Formby is 45 minutes from Blackpool by car. National Trust pinewoods, red squirrels, a wide flat beach and good lunch in the village. Here's how to do the day trip properly.",
  },
  {
    slug: "formby-beach-summer-guide",
    title: "Formby Beach in Summer: What You Need to Know Before You Go",
    excerpt: "Parking fills before noon on hot Saturdays. The tide can take most of the beach away by afternoon. And the walk from the car park is 15 minutes. Here's everything you actually need to know before you go.",
    author: "Clare",
    date: "May 7, 2026",
    readTime: "7 min read",
    categorySlug: "beaches",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E8A6E 100%)",
    image: "/blog-formby-summer-beach.jpg",
    metaTitle: "Formby Beach in Summer: Parking, Tide Times, Dogs and What to Expect",
    metaDescription: "The honest guide to Formby Beach in summer. Postcode L37 1YH, NT parking, tide times, dog rules, facilities and where to go for lunch after. From a local who knows.",
  },
  {
    slug: "the-sparrowhawk-formby-review",
    title: "The Sparrowhawk Formby: An Honest Local Review",
    excerpt: "It's Formby's most popular pub and most people who visit end up there at some point. Is it worth it? Short answer: yes. Here's the longer version.",
    author: "Clare",
    date: "May 7, 2026",
    readTime: "5 min read",
    categorySlug: "restaurants",
    gradient: "linear-gradient(135deg, #2C1810 0%, #8B4513 100%)",
    image: "/blog-sparrowhawk-formby-review.jpg",
    metaTitle: "The Sparrowhawk Formby Review: Food, Prices and Booking",
    metaDescription: "Honest review of The Sparrowhawk pub in Formby. Sunday roast, steaks, dog-friendly garden, prices and whether you need to book. Written by a Formby local.",
  },
  {
    slug: "wild-garlic-formby-pinewoods",
    title: "Wild Garlic at Formby Pinewoods: Where to Find It and What to Do With It",
    excerpt: "May is the month wild garlic takes over the woodland floor in Formby. Here's where to find it, when to go, and what Clare does with it at home.",
    author: "Clare",
    date: "May 17, 2026",
    readTime: "5 min read",
    categorySlug: "wildlife",
    gradient: "linear-gradient(135deg, #1A5C3A 0%, #2E8A6E 100%)",
    image: "/blog-wild-garlic-formby-pinewoods.jpg",
    metaTitle: "Wild Garlic at Formby Pinewoods: Where to Find It in May",
    metaDescription: "Wild garlic is at its peak in Formby pinewoods in May. Where to find it, when to go, how to pick it responsibly, and what to cook. Local guide from a Formby resident.",
  },
  {
    slug: "formby-june-school-holidays",
    title: "Formby in June: What to Expect When School Breaks Up",
    excerpt: "June is the sweet spot before August chaos. Clare's honest guide to what Formby is like when term ends and what to plan for.",
    author: "Clare",
    date: "May 18, 2026",
    readTime: "6 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E7A9A 100%)",
    image: "/blog-formby-june-pinewoods.jpg",
    metaTitle: "Formby in June: What to Expect in Early Summer",
    metaDescription: "June in Formby before the August peak. Beach, pinewoods, red squirrels, what gets busy and what stays quiet. Honest local guide from Clare.",
  },
  {
    slug: "formby-beach-late-may-2026",
    title: "Formby Beach Right Now: Late May Conditions, Parking and What to Expect",
    excerpt: "It's one of the nicest times to be at Formby Beach and also one of the busiest. Here's the honest late May guide: parking reality, tide timing, what the beach is actually like right now.",
    author: "Clare",
    date: "May 28, 2026",
    readTime: "5 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E8A6E 100%)",
    image: "/blog-formby-late-may-beach.jpg",
    metaTitle: "Formby Beach Late May 2026: Parking, Tides and What to Expect",
    metaDescription: "Late May at Formby Beach: what conditions are like, when the car park fills, tide timing, dog rules and where to go for lunch after. Written by a Formby local.",
  },
  {
    slug: "formby-red-squirrels-june",
    title: "Red Squirrels at Formby in June: One of the Better Months to Visit",
    excerpt: "Everyone knows about the autumn peak but June is actually a good time to see red squirrels at Formby. Young squirrels are out. The pinewoods are at their best. Here's what to know.",
    author: "Clare",
    date: "May 28, 2026",
    readTime: "5 min read",
    categorySlug: "wildlife",
    gradient: "linear-gradient(135deg, #8B6040 0%, #A8764A 100%)",
    image: "/blog-formby-red-squirrel-june.jpg",
    metaTitle: "Red Squirrels at Formby in June: Is It Worth Visiting?",
    metaDescription: "June is underrated for red squirrel spotting at Formby. Young squirrels are active, the pinewoods are green, and the summer crowds haven't fully arrived. Tips from a local who visits regularly.",
  },
  {
    slug: "sunset-formby-point",
    title: "Sunset at Formby Point: Why the Evening Visit Is Better Than the Afternoon",
    excerpt: "The sunset from Formby Point is one of the best things about living near here. Here's when to go, where to stand, and why the evening is genuinely worth planning around.",
    author: "Clare",
    date: "June 1, 2026",
    readTime: "4 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #8B3A0A 0%, #C4680A 100%)",
    image: "/blog-formby-sunset-point.jpg",
    metaTitle: "Sunset at Formby Point: When to Go and Where to Stand",
    metaDescription: "The sunset from Formby Point over the Irish Sea is genuinely spectacular. When it peaks, where to stand on the dunes, tide timing, and why the evening visit beats the afternoon. A local's guide.",
  },
  {
    slug: "formby-summer-holidays-2026",
    title: "Formby Summer Holidays 2026: Six Weeks with Kids, Honestly",
    excerpt: "Six weeks with the kids. Here is how we use Formby through the summer holidays: what works for different ages, when to go where, and how to avoid the August car park queue.",
    author: "Clare",
    date: "June 1, 2026",
    readTime: "6 min read",
    categorySlug: "family",
    gradient: "linear-gradient(135deg, #1C3220 0%, #2E6B3E 100%)",
    image: "/blog-formby-summer-pinewoods.jpg",
    metaTitle: "Formby Summer Holidays 2026: What to Do with Kids for Six Weeks",
    metaDescription: "How to use Formby through the school summer holidays. Beach timing, red squirrels, pinewoods walks, rainy day options, and what to avoid on August bank holiday weekend. Honest local guide.",
  },
  {
    slug: "formby-in-may",
    title: "Formby in May: Why It's One of the Best Months to Visit",
    excerpt: "May at Formby is genuinely brilliant. The beach is quiet, the pinewoods are at their greenest, the red squirrels are out, and the weather is the best it gets without the August crowds. Here's what makes it the local's favourite month.",
    author: "Clare",
    date: "April 12, 2026",
    readTime: "6 min read",
    categorySlug: "seasonal",
    gradient: "linear-gradient(135deg, #1C4A5A 0%, #2E6B3E 100%)",
    image: "/blog-card-seasonal.webp",
    metaTitle: "Formby in May: Best Things to Do, What to Expect",
    metaDescription: "May is one of the best times to visit Formby. Quieter beach, green pinewoods, red squirrels active, natterjack toads calling in the evenings. What to do, where to go, and what makes May special.",
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}

export function getBlogCategory(slug: string): BlogCategory | undefined {
  return BLOG_CATEGORIES.find((c) => c.slug === slug);
}
